const PLAYER_DEFAULT_HP = 3;

const PLAYER_JOIN_EVENT = 'PLAYER_JOIN';
const PLAYER_DISCONNECT_EVENT = 'PLAYER_DISCONNECT';
const PLAYER_UPDATE_EVENT = 'PLAYER_UPDATE';
const PLAYER_SHOOT_EVENT = 'PLAYER_SHOOT';
const PLAYER_DIE_EVENT = 'PLAYER_DIE';
const PLAYER_SPAWN_EVENT = 'PLAYER_SPAWN';
const HEART_SPAWN_EVENT = 'HEART_SPAWN';
const HEART_CONSUME_EVENT = 'HEART_CONSUME';
const XP_CONSUME_EVENT = 'XP_CONSUME';
const XP_SPAWN_EVENT = 'XP_SPAWN';
const XP_SPAWN_STATIC_EVENT = 'XP_SPAWN_STATIC';
const XP_SET_POS_EVENT = 'XP_SET_POS';