const PLAYER_DEFAULT_HP = 3;
const PLAYER_DEFAULT_XP = 1;
const PLAYER_DEFAULT_BULLET_TYPE = BULLET_TYPE.NORMAL;

const PLAYER_KEY_DOWN_EVENT = 'PLAYER_KEY_DOWN';
const PLAYER_KEY_UP_EVENT = 'PLAYER_KEY_UP';
const PLAYER_JOIN_EVENT = 'PLAYER_JOIN';
const PLAYER_DISCONNECT_EVENT = 'PLAYER_DISCONNECT';
const PLAYER_UPDATE_EVENT = 'PLAYER_UPDATE';
const PLAYER_SHOOT_EVENT = 'PLAYER_SHOOT';
const PLAYER_DIE_EVENT = 'PLAYER_DIE';